In [1]:
v1=[1,2,4]
v2=[3,4,6]
add=[v1[i]+v2[i] for i in range (len(v1))]
print(add)

[4, 6, 10]


In [2]:
dot=sum([v1[i]*v2[i] for i in range (len(v1))])
print(dot)

35


In [3]:
scalarProduct=[3* x for x in v1]
print(scalarProduct)

[3, 6, 12]


In [4]:
import numpy as np 
v1=np.array([1,2,4])
v2=np.array([3,4,6])
add=np.add(v1,v2)
print(add)
dot=np.dot(v1,v2)
print(dot)
scalarProduct=np.multiply(3,v1)
print(scalarProduct)

[ 4  6 10]
35
[ 3  6 12]


In [5]:
hadamard=v1*v2
print(hadamard)

[ 3  8 24]


In [11]:
v1=np.array([[1,2,4],[2,3,5], [3,4,6]])
v2=np.array([[3,4,6],[4,5,7],[5,6,8]])
cross=np.cross(v1,v2)
print(cross)

[[-4  6 -2]
 [-4  6 -2]
 [-4  6 -2]]


In [17]:
outerProduct=np.outer(v1,v2)
print(outerProduct)
a = np.array([1, 2,3])
b = np.array([2,3, 4])
outer = np.outer(a, b)
print(outer)


[[ 3  4  6  4  5  7  5  6  8]
 [ 6  8 12  8 10 14 10 12 16]
 [12 16 24 16 20 28 20 24 32]
 [ 6  8 12  8 10 14 10 12 16]
 [ 9 12 18 12 15 21 15 18 24]
 [15 20 30 20 25 35 25 30 40]
 [ 9 12 18 12 15 21 15 18 24]
 [12 16 24 16 20 28 20 24 32]
 [18 24 36 24 30 42 30 36 48]]
[[ 2  3  4]
 [ 4  6  8]
 [ 6  9 12]]


In [14]:
print(cross.shape)
print(outerProduct.shape)

(3, 3)
(9, 9)


In [15]:
KroneckerProduct=np.kron(v1,v2)
print

<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[0, 5], [6, 7]])
kron = np.kron(A, B)
print(kron)

[[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]
